View(COF)
attach(COF)
install.packages(c('caret'))
library(caret)
dmy <- dummyVars("~ .", data = COF, fullRank = T)
trsf <- data.frame(predict(dmy, newdata = COF))
str(trsf)
stacked_cof <- stack(trsf)
chisq.test(trsf)
plot(trsf)
