View(Computer_Data)
attach(Computer_Data)
install.packages(c('caret'))
library(caret)
dmy <- dummyVars("~ .", data = Computer_Data, fullRank = T)
trsf <- data.frame(predict(dmy, newdata = Computer_Data))
str(trsf)
summary(trsf)
sd(price)
sd(speed)
sd(hd)
sd(ram)
sd(screen)
sd(ads)
sd(trend)
var(price)
var(speed)
var(hd)
var(ram)
var(screen)
var(ads)
var(trend)
library(e1071)
skewness(price)
skewness(speed)
skewness(hd)
skewness(ram)
skewness(screen)
skewness(ads)
skewness(trend)
kurtosis(price)
kurtosis(speed)
kurtosis(hd)
kurtosis(ram)
kurtosis(screen)
kurtosis(ads)
kurtosis(trend)
plot(speed,price)
plot(hd,price)
plot(ram,price)
plot(screen,price)
plot(ads,price)
plot(trend,price)
plot(cd,price)
plot(multi,price)
plot(premium,price)
pairs(Computer_Data)
# Correlation Coefficient matrix - Strength & Direction of Correlation
cor(trsf)
model.computer <- lm(price~.,data = trsf)
summary(model.computer)
library(car)
influenceIndexPlot(model.computer)# errors are in point 1441 and 1701 so i deleting both the point
model1.computer <- lm(price~.,data = trsf[-c(1441,1701),])
summary(model1.computer)
influenceIndexPlot(model1.computer)
vif(model1.computer)
avPlots(model1.computer)# after AIC , i saw that there is no corelation between cd and multi so i will remove them
model2.computer <- lm(price ~ speed+hd+ram+screen+premium+ads+trend, data = trsf[-c(1441,1701)])
summary(model2.computer)
avPlots(model2.computer)
plot(model.computer)
qqPlot(model.computer)
